### ISSUE TITLE
[FEATURE] Тестировать контейнерную сборку перед релизом

### ISSUE THREAD

**Issue by mikhpo** [mikhpo/personal-website#171]
### Предполагаемое решение
https://stackoverflow.com/questions/70674664/how-to-build-run-and-call-docker-container-in-github-action:
```
...
jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v4
        with:
          context: .
          file: "Dockerfile.test"
          tags: localpytest:latest
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: false
      - name: Run Pytest
        uses: addnab/docker-run-action@v3
        with:
          image: localpytest:latest
          run: pytest

```
