### ISSUE TITLE
[FEATURE] Выделить статический анализ кода в отдельную джобу пайплайна

### ISSUE THREAD

**Issue by mikhpo** [mikhpo/personal-website#172]
### Запрос на доработку вызван какой-либо проблемой?

Джоба статического анализа может выполняться параллельно джобе тестирования. Она должна включать в себя проверки ruff и mypy. Можно предусмотреть возможность кэширования зависимостей Python (но можно ли тогда будет выполнять джобы паралльно?). 

### Дополнительная информация

Пример кэширования зависимостей Poetry:

```
steps:
- uses: actions/checkout@v4
- name: Install poetry
  run: pipx install poetry
- uses: actions/setup-python@v5
  with:
    python-version: '3.9'
    cache: 'poetry'
- run: poetry install
- run: poetry run pytest
```
